### PR TITLE
DI-84 initial version

### PR DESCRIPTION
**Pull request by sophie22**
Having resolved the variant calling by updating input files and parameters to the variant calling app, the functionality required from this app has been narrowed down to:
* report and exclude low covered PRS variants (based on a depth threshold provided by the user, default is 20x)
* output a filtered VCF in the correct format, excluding the low covered variants
* OPTIONAL report PRS variants that overlap with CNVs detected by GATK gCNV caller (only performed if CNV_segments.vcf input is provided)

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_CANRISK_vcf/5)

### CODE REVIEW

**Comment by sophie22** [comment]
exclusion is now optional: app-GX652q84037vk1jp035QbkJ2

job with exclusion (default)
https://platform.dnanexus.com/projects/GVgZqxQ4xVgz5FbVKG7gvjBY/monitor/job/GX65Ybj4xVgzQpXx2vy09p1B
job without exclusion
https://platform.dnanexus.com/projects/GVgZqxQ4xVgz5FbVKG7gvjBY/monitor/job/GX65g584xVgbZF5QB445kJBZ

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_CANRISK_vcf/5)* status: all files reviewed, 1 unresolved discussion (waiting on @sophie22)

___
*[`README.md` line 16 at r5](https://reviewable.io/reviews/eastgenomics/eggd_CANRISK_vcf/5#-NY3QZoQ7VePIOS4zA6s:-NY3QZoQ7VePIOS4zA6t:bq5kpo9) ([raw file](https://github.com/eastgenomics/eggd_CANRISK_vcf/blob/79da84e4731f9b12ea5186eaf107596c617881b6/README.md#L16)):*
> ```Markdown
> ## How does this app work?
> 
> The app normalises multiallelic variants and modifies the VCF to include ALTs in 0/0 positions.
> ```

We're no longer modifying the alts in this way right?



_Code quote:_
```Markdown
modifies the VCF to include ALTs in 0/0 positions
```

**Review by mattgarner — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_CANRISK_vcf/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sophie22)

___
*[`README.md` line 16 at r5](https://reviewable.io/reviews/eastgenomics/eggd_CANRISK_vcf/5#-NY3QZoQ7VePIOS4zA6s:-NY3Y_XP01T1ZqYt95PB:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_CANRISK_vcf/blob/79da84e4731f9b12ea5186eaf107596c617881b6/README.md#L16)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

We're no longer modifying the alts in this way right?
</blockquote></details>

Done

**Comment by sophie22** [comment]
resolves #3 and #4

**Pull request merged**
